### ISSUE TITLE
bugbugbug

### ISSUE THREAD

**Issue by dyx-max** [azmiao/pcrjjc_tw_new#6]
![Uploading 网页捕获_18-6-2023_124959_github.com.jpeg…]()

**Comment by azmiao** [comment]
嗯？你这图片我怎么加载不出来

**Comment by dyx-max** [comment]
![1687064344019](https://github.com/azmiao/pcrjjc_tw_new/assets/79912177/b03b2973-3a4f-4d17-88bf-3be4e453e0ea)
你这个变量不应该放在if里吧

**Comment by dyx-max** [comment]
详细查询插别人的时候报错

**Comment by azmiao** [comment]
> ![1687064344019](https://user-images.githubusercontent.com/79912177/246644511-b03b2973-3a4f-4d17-88bf-3be4e453e0ea.jpg) 你这个变量不应该放在if里吧

user_id是QQ，没关系的，你把你的日志截图重发一下

**Comment by azmiao** [comment]
哦后面日志显示好像确实有点问题哈，我改下

**Comment by azmiao** [comment]
@dyx-max 应该好了，之前没注意到抱歉
