### ISSUE TITLE
请教下新的配置文件如何获取

### ISSUE THREAD

**Issue by XingseLiuli** [azmiao/pcrjjc_tw_new#7]
更新4.0版本后data/data/tw.sonet.princessconnect/shared_prefs/tw.sonet.princessconnect.v2.playerprefs.xml这个路径已经找不到了

**Comment by XingseLiuli** [comment]
已经解决了，得root才行，抱歉打扰了ヽ(≧□≦)ノ

**Comment by azmiao** [comment]
嗯嗯，用模拟器就行，进游戏的时候关root，登陆完再开root去拿文件

**Comment by XingseLiuli** [comment]
好滴，感谢大佬
